### ISSUE TITLE
我的移动硬盘 按你说的方法没好用

### ISSUE THREAD

**Issue by liaodongxiaoxiao** [GcsSloop/MacDeveloper#1]
第四步，再插上，在 /Volumes 目录下看不到我的移动硬盘
还有 ：LABEL=魔法森林 none ntfs rw,auto,nobrowse
这个rw auto nobrowse之前不能有空格好像，有空格的情况下我的移动硬盘好像都没隐藏。

我的系统版本是：OS X 10.11.5

**Comment by GcsSloop** [comment]
这个是支持写入内容系统默认不允许在 ntfs格式的硬盘上写入文件，这是为了能够在ntfs格式的硬盘上写文件。
我的系统偶尔会不识别硬盘，我用不知道是为什么，重启系统就行了
LABEL 后面的第一个参数是你的硬盘名称

我的也是 OS X 10.11.5

**Comment by Piasy** [comment]
10.11.5 没用 +1，重启依然没用

**Comment by GcsSloop** [comment]
好吧，并不知道是什么原因，有人说用UUID可以，参见这篇文章 http://apple.macx.cn/thread-2134889-1-1.html 如果这也没用的话尝试一下插件，我记得有相关的ntfs支持插件。

**Comment by Piasy** [comment]
UUID 可以！
